### ISSUE TITLE
Plz make panorama load from url

### ISSUE THREAD

**Issue by kekedaine** [olexale/arkit_flutter_plugin#22]

**Comment by olexale** [comment]
Hi @kekedaine ,

I've added the `url` property to `ARKitMaterialProperty`. You may use it the same way `image` is used in `panorama` sample.
Those changes are not pushed to the pub yet, so you may play around with this functionality by using the plugin directly from GitHub like that:
```yaml
dependencies:
  arkit_plugin:
    git:
      url: https://github.com/olexale/arkit_flutter_plugin
```
