### ISSUE TITLE
Remove anchor from scene

### ISSUE THREAD

**Issue by RedJ0hn** [olexale/arkit_flutter_plugin#65]
Hi,
Thanks for help with identifying which dynamically loaded image was recognized. It works great.
I have another question. Is it possible to remove anchor from scene?

**Comment by olexale** [comment]
Hi, 
It must be possible, but you're the first who requested this functionality 😅
I'll add this possibility. Sorry for the inconvenience.

**Comment by RedJ0hn** [comment]
Hi,

**Comment by olexale** [comment]
I've just pushed the `removeAnchor` method. Could you please check whether it works for you?
In order to use the latest version you may update your `pubspec.yaml` file like that:
```yaml
dependencies:
  arkit_plugin:
    git:
      url: git://github.com/olexale/arkit_flutter_plugin.git
```
