### ISSUE TITLE
Version 0.5.2 is not on https://pub.dev/

### ISSUE THREAD

**Issue by dariocavada** [olexale/arkit_flutter_plugin#69]
I would like to use the referenceImageName that you fixed in the 0.5.2 version (https://github.com/olexale/arkit_flutter_plugin/blob/master/CHANGELOG.md) 

Do you plan to publish the new version ?
Is possible to use the version from github (master) ?

Thank you.

**Comment by olexale** [comment]
I have one more enhancement planned for the release, but you may use the version from GitHub. Change your `pubspec` file like that:
```yaml
dependencies:
  arkit_plugin:
    git: git://github.com/olexale/arkit_flutter_plugin.git
```
